### ISSUE TITLE
RuntimeError: size mismatch, m1: [19 x 8192], m2: [512 x 62] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266

### ISSUE THREAD

**Issue by SriKrishnaManoj** [ermongroup/PatchDrop#1]
I have been trying to reproduce the results of this implementation for fMoW dataset. When trying to run the pretrain.py file, I am getting the following error:
```
Traceback (most recent call last):
  File "pretrain.py", line 205, in <module>
    train(epoch)
  File "pretrain.py", line 84, in train
    preds_map = rnet.forward(inputs_map, args.model.split('_')[1], 'hr')#inputs_map
  File "/media/data/manoj/Manoj/Krishna_Manoj/fMOW/PatchDrop-master/models/resnet.py", line 102, in forward
    out = self.linear(out)
  File "/home/pytorch/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pytorch/.local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/pytorch/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [19 x 8192], m2: [512 x 62] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
```

I chose a batch size of 19, as the GPU memory is not sufficient for handling larger batch sizes. Can you please guide me?

Command used to execute the file: `python pretrain.py --model R34_fMoW --batch_size 19 --ckpt_hr_cl ./cv/tmp/final_ckpt_468 --max_epochs 64`

**Comment by uzkent** [comment]
@SriKrishnaManoj What is the size of your `inputs_map` tensor? Also, the batch size of `19` is very low to train the policy network. Based on my observation, it should at least be `512`.

**Comment by SriKrishnaManoj** [comment]
I resolved it by making changes as shown below in models/resnet.py in line 101 since I have restricted myself to fMoW dataset:
`out = F.avg_pool2d(out, 28)
`
 Batch size of more than 6 results in the following:
`RuntimeError: CUDA out of memory. Tried to allocate 12.50 MiB
`
I am running the code on Nvidia Titan V.

**Comment by uzkent** [comment]
What size of input images are you using?

**Comment by SriKrishnaManoj** [comment]
224 * 224

**Comment by uzkent** [comment]
You should not run out of memory with batch size of 6. Are you sure that you are fully utilizing the GPU?

**Comment by SriKrishnaManoj** [comment]
Yes, because if I increase it more than 6, I get CUDA out of memory error. 

Should lr_size be something other than 8(which is default value as given in line 45 of pretrain.py )?

Code is running on Device 0(Screenshot attached)
![Screenshot 2020-05-19 at 1 40 36 PM](https://user-images.githubusercontent.com/26005323/82301758-5537e900-99d6-11ea-80ea-9fe4874900bb.png)

**Comment by uzkent** [comment]
The lr_size depends on your application. You can set it to 56 pixels or 112 pixels for 224x224 pixels images. It can be 8 or 16 for 32x32 pixels CIFAR10 images. Again, it should not run out of memory with batch size of 6.  What is your policy network and classification network?

**Comment by SriKrishnaManoj** [comment]
Policy network and classification network are same as those discussed in the paper and implementation. Dataset, as mentioned above, is fMoW. I have been using lr_size as 56.

Can you please confirm if the code is running without the changes made in line no. 100 of `resnet.py` file as mentioned above(in the 2nd comment of this thread)? If the answer is yes, can you please share the command given to execute `pretrain.py` along with the arguments?

Also, with batch size of 6, I am getting an accuracy of 0.047, which I believe are very poor. 

I don't understand where I am going wrong.

**Comment by uzkent** [comment]
I can run the `pretrain.py` script on `fMoW dataset` with the batch size of 64 using a single GPU.   Also, I just pushed my updates that should resolve the conflict you mentioned in the first message. Finally, you can not train `Policy Gradients with Reinforce` using small batch sizes. That is why it should be run with very large batch sizes, minimum 512 based on my observation.
